name: build
on:
  workflow_call:
jobs:
  check:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: cache packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: restore dependencies
        run: dotnet restore --locked-mode
      - name: build
        run: dotnet build --no-restore --configuration Release
      - name: run tests
        run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings test/coverlet.runsettings --blame-hang-timeout 5m
